name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Kodu Cek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Bagimliliklari Kur
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          pip install --upgrade pip
          pip install buildozer cython

      - name: APK Derle
        run: |
          buildozer init
          sed -i 's/#android.permissions = READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE/android.permissions = READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE,MANAGE_EXTERNAL_STORAGE/' buildozer.spec
          sed -i 's/#android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
          yes | buildozer android debug

      - name: APK'yi Yukle
        uses: actions/upload-artifact@v4
        with:
          name: GD-Save-Tool-APK
          path: bin/*.apk
